import { Injectable, BadRequestException } from '@nestjs/common';
import { PrismaService } from '../common/services';
import { ConfigService } from '@nestjs/config';
import { existsSync, mkdirSync, unlinkSync } from 'fs';
import { join, extname } from 'path';
import { v4 as uuidv4 } from 'uuid';
import { User } from '@prisma/client';

@Injectable()
export class FilesService {
  constructor(
    private prisma: PrismaService,
    private configService: ConfigService,
  ) {
    // Ensure uploads directory exists
    const uploadDir =
      this.configService.get<string>('files.uploadDir') ||
      join(process.cwd(), 'uploads');
    if (!existsSync(uploadDir)) {
      mkdirSync(uploadDir, { recursive: true });
    }
  }

  async uploadFile(file: Express.Multer.File, user: User, postId?: string) {
    if (!file) {
      throw new BadRequestException('No file uploaded');
    }

    console.log('Received file upload request:', {
      originalName: file.originalname,
      mimetype: file.mimetype,
      size: file.size,
      destination: file.destination || 'unknown',
      filename: file.filename || 'unknown',
      userId: user.id,
      postId: postId || 'none',
    });

    // Validate file size
    const maxFileSize =
      this.configService.get<number>('files.maxFileSize') || 5 * 1024 * 1024;
    if (file.size > maxFileSize) {
      throw new BadRequestException(
        `File size exceeds the limit of ${maxFileSize / 1024 / 1024}MB`,
      );
    }

    // Validate file type
    const allowedMimeTypes = this.configService.get<string[]>(
      'files.allowedMimeTypes',
    ) || ['image/jpeg', 'image/png', 'image/gif', 'image/webp'];
    if (!allowedMimeTypes.includes(file.mimetype)) {
      throw new BadRequestException(
        `File type ${file.mimetype} is not allowed`,
      );
    }

    // Use the filename generated by FileInterceptor if available
    const filePath = file.path
      ? file.path.replace(process.cwd(), '').replace(/\\/g, '/')
      : join(
          'uploads',
          file.filename || `${uuidv4()}${extname(file.originalname)}`,
        );

    console.log('File will be saved with path:', filePath);

    // Save file info to database
    const fileRecord = await this.prisma.file.create({
      data: {
        filename: file.originalname,
        path: filePath,
        mimetype: file.mimetype,
        size: file.size,
        userId: user.id,
        ...(postId && { postId }),
      },
    });

    return fileRecord;
  }

  async getFileById(id: string) {
    const file = await this.prisma.file.findUnique({
      where: { id },
    });

    if (!file) {
      throw new BadRequestException(`File with ID ${id} not found`);
    }

    return file;
  }

  async deleteFile(id: string, userId: string) {
    // Check if file exists and belongs to user
    const file = await this.prisma.file.findFirst({
      where: {
        id,
        userId,
      },
    });

    if (!file) {
      throw new BadRequestException(
        `File with ID ${id} not found or doesn't belong to you`,
      );
    }

    // Delete file from database
    await this.prisma.file.delete({
      where: { id },
    });

    // Try to delete file from disk
    try {
      const filePath = join(process.cwd(), file.path);
      if (existsSync(filePath)) {
        unlinkSync(filePath);
      }
    } catch (error) {
      console.error(`Error deleting file from disk: ${error.message}`);
    }

    return { success: true };
  }

  async getFilesByPostId(postId: string) {
    return this.prisma.file.findMany({
      where: { postId },
    });
  }

  async getUserProfilePicture(userId: string) {
    // Get the user's profile picture (most recent one marked as profile pic)
    const profilePic = await this.prisma.file.findFirst({
      where: {
        userId: userId,
        isProfilePic: true,
      },
      orderBy: {
        createdAt: 'desc',
      },
    });

    return profilePic;
  }

  async markAsProfilePicture(fileId: string) {
    // Mark a file as a profile picture
    return this.prisma.file.update({
      where: { id: fileId },
      data: { isProfilePic: true },
    });
  }

  async resetUserProfilePictures(userId: string) {
    // Reset all profile pictures for a user
    return this.prisma.file.updateMany({
      where: {
        userId: userId,
        isProfilePic: true,
      },
      data: {
        isProfilePic: false,
      },
    });
  }
}
